name: TuriCheck CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install
    
    - name: Build Move
      run: |
        curl -fLSs https://github.com/MystenLabs/sui/releases/download/sui-v1.0.0/sui-ubuntu-x86_64
        chmod +x sui-ubuntu-x86_64
        cd contracts/move && ../../sui-ubuntu-x86_64 move build
    
    - name: Build frontend
      run: |
        cd apps/frontend
        yarn build